#Generated by VisualGDB (http://visualgdb.com)
#DO NOT EDIT THIS FILE MANUALLY UNLESS YOU ABSOLUTELY NEED TO
#USE VISUALGDB PROJECT PROPERTIES DIALOG INSTEAD

DESTDIR = Debug
CONFIG += debug

DEFINES += 
LIBS += -LC:\SysGCC\Raspberry\arm-linux-gnueabihf\sysroot\usr\include
INCLUDEPATH += 
QMAKE_LFLAGS += -lnfc
QMAKE_CXXFLAGS += -ggdb -lnfc 
QMAKE_CFLAGS += -ggdb -lnfc 
COMMONFLAGS += -lnfc
