#Generated by VisualGDB (http://visualgdb.com)
#DO NOT EDIT THIS FILE MANUALLY UNLESS YOU ABSOLUTELY NEED TO
#USE VISUALGDB PROJECT PROPERTIES DIALOG INSTEAD

DESTDIR = Debug
CONFIG += debug

QT += sql
DEFINES += 
LIBS += -LC:\SysGCC\Raspberry\arm-linux-gnueabihf\sysroot\usr\include -lpthread -lwiringPi -lmosquitto
INCLUDEPATH += 
QMAKE_LFLAGS += 
QMAKE_CXXFLAGS += -ggdb 
QMAKE_CFLAGS += -ggdb 
COMMONFLAGS += -lnfc
